name: Deploy Azure Function App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Azure PowerShell
      uses: azure/powershell@v1
      with:
        azVersion: 'latest'

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Functions
      uses: azure/functions-action@v1
      with:
        app-name: AADUserDataToSnowflake
        package: '.'
