name: Deploy Azure Function App

on:
  push:
    branches:
      - main  # Triggers workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu environment

    steps:
    - name: Checkout code  # Step to check out your repository's code
      uses: actions/checkout@v2

    - name: Login to Azure using Service Principal
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Functions  # Step to deploy the function app using publish profile
      uses: azure/functions-action@v1
      with:
        app-name: 'AADUserDataToSnowflake'  # Replace with your actual Function App name
        publish-profile: ${{ secrets.AZURE_PUB_PROFILE }}
        package: '.'  # Deploy the current directory
