name: Deploy Azure Function App

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Azure PowerShell
      uses: azure/powershell@v1
      with:
        azVersion: 'latest'  # This specifies the Azure PowerShell module version

    - name: Deploy to Azure Functions
      uses: azure/functions-action@v1
      with:
        app-name: 'AADUserDataToSnowflake'  # Replace with your Azure Function App name
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        package: '.'

